create table "public"."milestones" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "project_id" bigint,
    "text" text
);


alter table "public"."milestones" enable row level security;

create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "agreement_id" text,
    "title" text,
    "description" text,
    "catagory" text,
    "start_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "owner" text not null,
    "worker" text,
    "additional_information" json
);


alter table "public"."projects" enable row level security;

CREATE UNIQUE INDEX milestones_pkey ON public.milestones USING btree (id);

CREATE UNIQUE INDEX projects_agreement_id_key ON public.projects USING btree (agreement_id);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

alter table "public"."milestones" add constraint "milestones_pkey" PRIMARY KEY using index "milestones_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."milestones" add constraint "milestones_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) not valid;

alter table "public"."milestones" validate constraint "milestones_project_id_fkey";

alter table "public"."projects" add constraint "projects_agreement_id_key" UNIQUE using index "projects_agreement_id_key";


